edatribe/models.py
"""

这里是数据模型

"""
from datetime import datetime
from edatribe.extensions import db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime

# 管理员模型
class Admin(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20))
    password_hash = db.Column(db.String(128))

# 密码进行哈希加密存储
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def validate_password(self, password):
        return check_password_hash(self.password_hash, password)


# 番剧模型
class Anime(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name_cn = db.Column(db.String)
    name_en = db.Column(db.String)
    episodes = db.Column(db.Integer)
    filesize = db.Column(db.Integer)  # 单位是字节
    update_time = db.Column(db.DateTime, default=datetime.utcnow, index=True)
    is_dual = db.Column(db.Integer)
    

edatribe/forms.py
# 表单
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, TextAreaField, ValidationError, HiddenField, \
    BooleanField, PasswordField
from wtforms.validators import DataRequired, Email, Length, Optional, URL


# 登录表单
class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(1, 20)])
    password = PasswordField('Password', validators=[DataRequired(), Length(1, 128)])
    submit = SubmitField('Log in')


# 新增番剧表单
class PostForm(FlaskForm):
    name_cn = StringField('中文名')
    name_en = StringField('英文名')
    episodes = StringField('集数')
    filesize = StringField('大小')
    is_dual = BooleanField('双语')
    submit = SubmitField('提交')

edatribe/__init__.py
from flask import Flask, render_template
from edatribe.config import config
import os
from edatribe.extensions import db, login_manager, bootstrap, csrf
from edatribe.blueprints.admin import admin_bp
from edatribe.blueprints.home import home_bp
from edatribe.blueprints.auth import auth_bp
import click
from flask_wtf.csrf import CSRFError


# 定义工厂函数（工厂函数也是一个函数，config_filename是函数的型参，应用函数时导入实际配置文件。
def create_app(config_name=None):
    if config_name is None:
        config_name = os.getenv('FLASK_CONFIG', 'development')
    
    app = Flask(__name__)
    app.config.from_object(config[config_name])  # 从对象导入,配置文件里有个字典对象

    register_extensions(app)  # 注册扩展（扩展初始化）
    register_blueprints(app)  # 注册蓝本
    register_commands(app)  # 注册命令
    register_errors(app) # 注册错误处理
    return app


# 扩展初始化
def register_extensions(app): 
    db.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)
    csrf.init_app(app)



# 蓝本
def register_blueprints(app):
    app.register_blueprint(home_bp)
    app.register_blueprint(admin_bp, url_prefix='/admin')
    app.register_blueprint(auth_bp, url_prefix='/auth')

# 错误处理
def register_errors(app):
    @app.errorhandler(CSRFError)
    def handle_csrf_error(e):
        return render_template('errors/400.html', description=e.description), 400
    @app.errorhandler(400)
    def bad_request(e):
        return render_template('errors/400.html'), 400

    @app.errorhandler(404)
    def page_not_found(e):
        return render_template('errors/404.html'), 404

    @app.errorhandler(500)
    def internal_server_error(e):
        return render_template('errors/500.html'), 500

# 注册命令
def register_commands(app):

    # 注册管理员命令
    @app.cli.command()
    @click.option('--username', prompt=True, help='The username used to login.')
    @click.option('--password', prompt=True, hide_input=True, confirmation_prompt=True, help='The password used to login.')
    def admin(username, password):
        """Create user."""
        db.create_all()

        from edatribe.models import Admin
        user = Admin.query.first()
        if user is not None:
            click.echo('Updating user...')
            user.username = username
            user.set_password(password)  # 设置密码
        else:
            click.echo('Creating user...')
            user = Admin(username=username)
            user.set_password(password)  # 设置密码
            db.session.add(user)

        db.session.commit()  # 提交数据库会话
        click.echo('Done.')

    # 初始化数据库命令
    @app.cli.command()
    @click.option('--drop', is_flag=True, help='Create after drop.')
    def initdb(drop):
        """Initialize the database."""
        if drop:
            click.confirm('This operation will delete the database, do you want to continue?', abort=True)
            db.drop_all()
            click.echo('Drop tables.')
        db.create_all()
        click.echo('Initialized database.')

    # 生成测试数据
    @app.cli.command()
    def forge():
        """Generate fake data."""
        db.create_all()
        from edatribe.models import Anime

        # 全局的两个变量移动到这个函数内anime
        anime = [
            {'name_en': 'My Neighbor Totoro', 'filesize': '1988'},
            {'name_en': 'Dead Poets Society', 'filesize': '1989'},
            {'name_en': 'A Perfect World', 'filesize': '1993'},
            {'name_en': 'Leon', 'filesize': '1994'},
            {'name_en': 'Mahjong', 'filesize': '1996'},
            {'name_en': 'Swallowtail Butterfly', 'filesize': '1996'},
            {'name_en': 'King of Comedy', 'filesize': '1999'},
            {'name_en': 'Devils on the Doorstep', 'filesize': '1999'},
            {'name_en': 'WALL-E', 'filesize': '2008'},
            {'name_en': 'The Pork of Music', 'filesize': '2012'},
        ]

        for i in anime:
            anime = Anime(name_en=i['name_en'], filesize=i['filesize'])
            db.session.add(anime)

        db.session.commit()
        click.echo('Done.')

edatribe/blueprints/admin.py
# 管理页蓝图
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required
from edatribe.forms import PostForm
from edatribe.extensions import db
from edatribe.models import Anime


admin_bp = Blueprint('admin', __name__)


# 番剧管理
@admin_bp.route('/anime')
@login_required
def anime():
    return render_template('admin/anime.html')


# 字幕管理 
@admin_bp.route('/cc')
@login_required
def cc():
    return render_template('admin/cc.html')

# 标签管理 
@admin_bp.route('/tab')
@login_required
def tab():
    return render_template('admin/tab.html')

# 标签管理 
@admin_bp.route('/other')
@login_required
def other():
    return render_template('admin/other.html')

# 新增番剧
@admin_bp.route('/post', methods=['GET', 'POST'])
@login_required
def post():
    form = PostForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            new_post = Anime(name_cn=form.name_cn.data,
                            is_dual=form.is_dual.data,
                            name_en=form.name_en.data,
                            episodes=form.episodes.data,
                            filesize=form.filesize.data)
            db.session.add(new_post)
            db.session.commit()
            flash("success", 'success')
            return redirect(url_for('admin.post'))
    else:
        return render_template('admin/post.html', form=form)

edatribe/blueprints/auth.py
# 用户登录认证蓝图
from flask import render_template, flash, redirect, url_for, Blueprint, request, url_for
from flask_login import login_user, logout_user, login_required, current_user
from edatribe.forms import LoginForm
from edatribe.models import Admin
from edatribe.utils import redirect_back

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/')
def index():
    return "这是登录页"


# 登录
@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('auth.index'))

    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        admin = Admin.query.first()
        if admin:
            if username == admin.username and admin.validate_password(password):
                login_user(admin)
                flash('Welcome back.', 'info')
                return redirect(url_for('home.index'))
            flash('Invalid username or password.', 'warning')
        else:
            flash('No account.', 'warning')
    return render_template('auth/login.html', form=form)

# 注销
@auth_bp.route('/logout')
@login_required  # 用于视图保护，后面会详细介绍
def logout():
    logout_user()
    return redirect('/')

edatribe/blueprints/home.py
# 主页蓝图
from flask import Blueprint, render_template


home_bp = Blueprint('home', __name__)


@home_bp.route('/')
def index():
    return render_template('website/index.html')

edatribe/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/perfect_blue.min.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">
    {% endblock head %}
</head>

<body>
    {% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('home.index') }}">英配部落</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    {{ render_nav_item('home.index', '主页') }}
                    {% if current_user.is_authenticated %}
                    {{ render_nav_item('admin.anime', '番剧管理') }}
                    {{ render_nav_item('admin.cc', '字幕管理') }}
                    {{ render_nav_item('admin.tab', '标签管理') }}
                    {{ render_nav_item('admin.other', '其他管理') }}
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                    {{ render_nav_item('admin.post', '新增') }}
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% endblock nav %}

    <main class="container">
        {% for message in get_flashed_messages(with_categories=True) %}
        <div class="alert alert-{{ message[0] }}" role="alert">
            <button type="button" class="close" data-dismiss="alert" >&times;</button>
            {{ message[1] }}
        </div>
        {% endfor %}
        {% block content %} {% endblock content %}
    </main>
</body>

<footer>
    <div>
        {% block footer %}
        <p class="float-left">
            <small> &copy; 2020 - EDATRIBE
            </small>
        </p>
        <p class="float-right">
            <small>
                {% if current_user.is_authenticated %}
                <a href="{{ url_for('auth.logout', next=request.full_path) }}">Logout</a>
                {% else %}
                <a href="{{ url_for('auth.login', next=request.full_path) }}">Login</a>
                {% endif %}
            </small>
        </p>
        {% endblock footer %}
    </div>
</footer>

{% block scripts %}
<script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.2.1.slim.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/script.js') }}"></script>
{% endblock %}

</html>

edatribe/templates/website/index.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h2>
        英配部落
    </h2>
</div>
{% endblock content %}